monosandbox-app:
    image: babagay/sandbox
    container_name: app
    cpu_shares: 100
    mem_limit: 262144000
    environment:
        - SPRING_PROFILES_ACTIVE=prod,swagger
        - SPRING_DATASOURCE_URL=jdbc:postgresql://monosandbox-postgresql:5432/monodb
        - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=monosandbox-elasticsearch:9300
    ports:
        - 80:8080
monosandbox-postgresql:
    cpu_shares: 100
    mem_limit: 262144000
    extends:
        file: postgres/postgres-sameersbn.yml
        service: monosandbox-postgresql
monosandbox-elasticsearch:
    cpu_shares: 100
    mem_limit: 262144000
    extends:
        file: elasticsearch.yml
        service: monosandbox-elasticsearch
