version: '2'
services:
    monosandbox-app:
        image: monosandbox
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://monosandbox-postgresql:5432/monoSandbox
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=monosandbox-elasticsearch:9300
        ports:
            - 8080:8080
    monosandbox-postgresql:
        extends:
            file: postgresql.yml
            service: monosandbox-postgresql
    monosandbox-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: monosandbox-elasticsearch
