version: '2'
services:
    monosandbox-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/monoSandbox/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=monoSandbox
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
