version: '3'
services:
    mysql:
        # image: babagay/mysql
        build:
          context: .
          dockerfile: mysql/Dockerfile
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret_pw
        ports:
            - "3306:3306"
        volumes:
            - d:/data:/var/lib/mysql
